language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
branches:
  - master
  - development
script:
  - npm test
after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run test:coverage:travis
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
