language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      branches:
        - master
        - development
      script:
        - npm test
      after_script:
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run test:coverage:travis
    - stage: npm release
      if: tag IS present
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
